services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  notifique:
    image: notifique:v0-service
    environment:
      - GIN_MODE=release
      - LOW_PRIORITY_QUEUE=notifique-low
      - MEDIUM_PRIORITY_QUEUE=notifique-medium
      - HIGH_PRIORITY_QUEUE=notifique-high
      - RABBITMQ_URL=amqp://rabbitmq:5672/
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/notifique?sslmode=disable
      - BROKER_CAPACITY=10
      - REDIS_URL=redis://redis:6379
      - API_VERSION=/v0
      - REQUESTS_PER_SECOND=100
      - CACHE_TTL_IN_SECONDS=60
      - JWKS_URL=https://cognito-idp.localhost.localstack.cloud:4566/us-east-1_2c9d52698930409287c7bae7a1649d2a/.well-known/jwks.json
    ports:
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_started
      localstack:
        condition: service_healthy

  # dynamodb-local:
  #   image: amazon/dynamodb-local:2.4.0
  #   environment:
  #     - name=value
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./volume/dynamodb:/home/dynamodblocal/data

  postgres:
    image: postgres:16.3
    ports:
      - 5432:5432
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notifique
      - POSTGRES_PASSWORD=postgres

  rabbitmq:
    image: rabbitmq:3.13.3
    ports:
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3

  redis:
    image: redis:7.4-rc1-alpine
    ports:
      - 6379:6379
