services:
  notifique:
    image: notifique:v0.1.0
    environment:
      - GIN_MODE=release
    ports:
      - 8080:8080

  dynamodb-local:
    image: amazon/dynamodb-local:2.4.0
    environment:
      - name=value
    ports:
      - 8000:8000
    volumes:
      - ./volumes/dynamodb:/home/dynamodblocal/data

  postgres:
    image: postgres:16.3
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notifique
      - POSTGRES_PASSWORD=postgres
