// Code generated by MockGen. DO NOT EDIT.
// Source: ./controllers/distribution_lists.go
//
// Generated by this command:
//
//	mockgen -source=./controllers/distribution_lists.go -destination ./test/mocks/distribution_lists.go
//

// Package mock_controllers is a generated GoMock package.
package mock_controllers

import (
	reflect "reflect"

	dto "github.com/notifique/dto"
	gomock "go.uber.org/mock/gomock"
	context "golang.org/x/net/context"
)

// MockDistributionListStorage is a mock of DistributionListStorage interface.
type MockDistributionListStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDistributionListStorageMockRecorder
	isgomock struct{}
}

// MockDistributionListStorageMockRecorder is the mock recorder for MockDistributionListStorage.
type MockDistributionListStorageMockRecorder struct {
	mock *MockDistributionListStorage
}

// NewMockDistributionListStorage creates a new mock instance.
func NewMockDistributionListStorage(ctrl *gomock.Controller) *MockDistributionListStorage {
	mock := &MockDistributionListStorage{ctrl: ctrl}
	mock.recorder = &MockDistributionListStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistributionListStorage) EXPECT() *MockDistributionListStorageMockRecorder {
	return m.recorder
}

// AddRecipients mocks base method.
func (m *MockDistributionListStorage) AddRecipients(ctx context.Context, distlistName string, recipients []string) (*dto.DistributionListSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecipients", ctx, distlistName, recipients)
	ret0, _ := ret[0].(*dto.DistributionListSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRecipients indicates an expected call of AddRecipients.
func (mr *MockDistributionListStorageMockRecorder) AddRecipients(ctx, distlistName, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecipients", reflect.TypeOf((*MockDistributionListStorage)(nil).AddRecipients), ctx, distlistName, recipients)
}

// CreateDistributionList mocks base method.
func (m *MockDistributionListStorage) CreateDistributionList(ctx context.Context, distributionList dto.DistributionList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDistributionList", ctx, distributionList)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDistributionList indicates an expected call of CreateDistributionList.
func (mr *MockDistributionListStorageMockRecorder) CreateDistributionList(ctx, distributionList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDistributionList", reflect.TypeOf((*MockDistributionListStorage)(nil).CreateDistributionList), ctx, distributionList)
}

// DeleteDistributionList mocks base method.
func (m *MockDistributionListStorage) DeleteDistributionList(ctx context.Context, distlistName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDistributionList", ctx, distlistName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDistributionList indicates an expected call of DeleteDistributionList.
func (mr *MockDistributionListStorageMockRecorder) DeleteDistributionList(ctx, distlistName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDistributionList", reflect.TypeOf((*MockDistributionListStorage)(nil).DeleteDistributionList), ctx, distlistName)
}

// DeleteRecipients mocks base method.
func (m *MockDistributionListStorage) DeleteRecipients(ctx context.Context, distlistName string, recipients []string) (*dto.DistributionListSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipients", ctx, distlistName, recipients)
	ret0, _ := ret[0].(*dto.DistributionListSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecipients indicates an expected call of DeleteRecipients.
func (mr *MockDistributionListStorageMockRecorder) DeleteRecipients(ctx, distlistName, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipients", reflect.TypeOf((*MockDistributionListStorage)(nil).DeleteRecipients), ctx, distlistName, recipients)
}

// GetDistributionLists mocks base method.
func (m *MockDistributionListStorage) GetDistributionLists(ctx context.Context, filter dto.PageFilter) (dto.Page[dto.DistributionListSummary], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistributionLists", ctx, filter)
	ret0, _ := ret[0].(dto.Page[dto.DistributionListSummary])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistributionLists indicates an expected call of GetDistributionLists.
func (mr *MockDistributionListStorageMockRecorder) GetDistributionLists(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistributionLists", reflect.TypeOf((*MockDistributionListStorage)(nil).GetDistributionLists), ctx, filter)
}

// GetRecipients mocks base method.
func (m *MockDistributionListStorage) GetRecipients(ctx context.Context, distlistName string, filter dto.PageFilter) (dto.Page[string], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipients", ctx, distlistName, filter)
	ret0, _ := ret[0].(dto.Page[string])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipients indicates an expected call of GetRecipients.
func (mr *MockDistributionListStorageMockRecorder) GetRecipients(ctx, distlistName, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipients", reflect.TypeOf((*MockDistributionListStorage)(nil).GetRecipients), ctx, distlistName, filter)
}
